//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artistas()
        {
            this.Albumes = new HashSet<Albumes>();
            this.Canciones = new HashSet<Canciones>();
        }
    
        public int IdArtista { get; set; }
        public string NombreArtistico { get; set; }
        public string PaisOrigen { get; set; }
        public Nullable<System.DateTime> FechaDebut { get; set; }
        public string FotoUrl { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Albumes> Albumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Canciones> Canciones { get; set; }
    }
}
