//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudiolibrosGuardados
    {
        public int IdAudiolibro { get; set; }
        public int IdUsuario { get; set; }
        public string VideoId { get; set; }
        public string Titulo { get; set; }
        public string CanalTitulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<int> DuracionSegundos { get; set; }
        public string ThumbnailUrl { get; set; }
        public string ThumbnailMediumUrl { get; set; }
        public string ThumbnailHighUrl { get; set; }
        public string TipoContenido { get; set; }
        public System.DateTime FechaGuardado { get; set; }
        public bool Activo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
