//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Canciones()
        {
            this.Favoritos = new HashSet<Favoritos>();
            this.HistorialReproduccion = new HashSet<HistorialReproduccion>();
            this.PlaylistDetalle = new HashSet<PlaylistDetalle>();
            this.RecomendacionesUsuario = new HashSet<RecomendacionesUsuario>();
        }
    
        public int IdCancion { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> DuracionSegundos { get; set; }
        public int AnioLanzamiento { get; set; }
        public string PreviewUrl { get; set; }
        public string AudioUrl { get; set; }
        public string ImagenUrl { get; set; }
        public string FuenteApi { get; set; }
        public string IdExternoApi { get; set; }
        public int IdArtista { get; set; }
        public Nullable<int> IdAlbum { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public long Reproducciones { get; set; }
        public bool EsExplIcita { get; set; }
        public bool Activo { get; set; }
    
        public virtual Albumes Albumes { get; set; }
        public virtual Artistas Artistas { get; set; }
        public virtual Generos Generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoritos> Favoritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialReproduccion> HistorialReproduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistDetalle> PlaylistDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecomendacionesUsuario> RecomendacionesUsuario { get; set; }
    }
}
