//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoritos
    {
        public int IdFavorito { get; set; }
        public int IdUsuario { get; set; }
        public int IdCancion { get; set; }
        public System.DateTime FechaAgregado { get; set; }
    
        public virtual Canciones Canciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
