//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialReproduccion
    {
        public int IdHistorial { get; set; }
        public int IdUsuario { get; set; }
        public int IdCancion { get; set; }
        public System.DateTime FechaReproduccion { get; set; }
        public Nullable<int> SegundosEscuchados { get; set; }
        public bool Completa { get; set; }
    
        public virtual Canciones Canciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
