//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarracionesDeportivas
    {
        public int IdNarracion { get; set; }
        public string VideoId { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string CanalYoutube { get; set; }
        public string ThumbnailUrl { get; set; }
        public string UrlYoutube { get; set; }
        public Nullable<int> DuracionSegundos { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Deporte { get; set; }
        public string EquipoLocal { get; set; }
        public string EquipoVisitante { get; set; }
        public string Evento { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public string Marcador { get; set; }
        public int IdUsuario { get; set; }
        public bool EsFavorito { get; set; }
        public string Notas { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Activo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
