//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistDetalle
    {
        public int IdPlaylistDetalle { get; set; }
        public int IdPlaylist { get; set; }
        public int IdCancion { get; set; }
        public System.DateTime FechaAgregado { get; set; }
        public Nullable<int> OrdenCancion { get; set; }
    
        public virtual Canciones Canciones { get; set; }
        public virtual Playlists Playlists { get; set; }
    }
}
