//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistCanciones
    {
        public int IdPlaylistCancion { get; set; }
        public int IdPlaylist { get; set; }
        public string VideoId { get; set; }
        public string Titulo { get; set; }
        public string Artista { get; set; }
        public string Portada { get; set; }
        public System.DateTime FechaAgregado { get; set; }
    
        public virtual Playlists Playlists { get; set; }
    }
}
