//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenciasUsuario
    {
        public int IdPreferencia { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> DecadaPreferida { get; set; }
        public Nullable<int> IdGeneroFavorito { get; set; }
        public string ModoRecomendacion { get; set; }
    
        public virtual Generos Generos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
