//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sputiffyEntities1 : DbContext
    {
        public sputiffyEntities1()
            : base("name=sputiffyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albumes> Albumes { get; set; }
        public virtual DbSet<Artistas> Artistas { get; set; }
        public virtual DbSet<Canciones> Canciones { get; set; }
        public virtual DbSet<Favoritos> Favoritos { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<HistorialReproduccion> HistorialReproduccion { get; set; }
        public virtual DbSet<PlaylistCanciones> PlaylistCanciones { get; set; }
        public virtual DbSet<PlaylistDetalle> PlaylistDetalle { get; set; }
        public virtual DbSet<Playlists> Playlists { get; set; }
        public virtual DbSet<PreferenciasUsuario> PreferenciasUsuario { get; set; }
        public virtual DbSet<RecomendacionesUsuario> RecomendacionesUsuario { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<vw_Usuarios_AnioBaseRecomendacion> vw_Usuarios_AnioBaseRecomendacion { get; set; }
        public virtual DbSet<AudiolibrosGuardados> AudiolibrosGuardados { get; set; }
        public virtual DbSet<CancionesOffline> CancionesOffline { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
