//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sputiffy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Usuarios_AnioBaseRecomendacion
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string NombreUsuario { get; set; }
        public string Correo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<int> AnioNacimiento { get; set; }
        public Nullable<int> AnioBaseRecomendacion { get; set; }
    }
}
